### ISSUE TITLE
Mac Install Instructions needs to be revised. 

### ISSUE THREAD

**Issue by OldSubSailor** [w8sl/Ortho4XP#2]
Homebrew call no longer used ruby, the new call is bash shell:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by w8sl** [comment]
Install instructions for all systems, requirements and "install_mac.sh" updated. Comments/review much appreciated - before ev. pull request into the official repository.

**Comment by OldSubSailor** [comment]
Apple keeps claiming that they are going to delete ruby from macOS some day, but when that will be?. 
However, the Homebrew website homepage has already changed to the bash format; and had made the install line copy "clickable" for those who need it.
https://brew.sh

**Comment by w8sl** [comment]
Thank you for your suggestions! Clickable install instructions in html format can be a future.

**Comment by OldSubSailor** [comment]
Well, I have never had this happen before until I got this Man Mini and Sonoma. 
**Homebrew would not run until if followed the brew install recommendation:**
Run this command in your terminal to add Homebrew to your PATH:
    eval "$(/opt/homebrew/bin/brew shellenv)"
So I suggest that you go ahead and include it in the install instructions also.

**Comment by w8sl** [comment]
It usually looks like this:

 Next steps:
- Run these two commands in your terminal to add Homebrew to your PATH:

    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/YOUR ACCOUNT NAME/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"

I have added this info in closed issue 210: https://github.com/oscarpilote/Ortho4XP/issues/210#issuecomment-1795356672

**Comment by OldSubSailor** [comment]
it is still not "sticking" from .zproflie

# Setting PATH for Python 3.11
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.11/bin:${PATH}"
export PATH


eval "$(/opt/homebrew/bin/brew shellenv)"

**Comment by w8sl** [comment]
Never had this problem with Homebrew Python3.11
Terminal command: "which python3.11" shows:
/opt/homebrew/bin/python3.11 (it is specific to Apple Silicon)
If something else - try: brew link python@3.11

**Comment by OldSubSailor** [comment]
I sure seem to remember finding "You can also test my unofficial branch: Progressive_XP11” when I was up in East Texas. I think that it even had that name. Am I misremembering and not finding it now?

**Comment by OldSubSailor** [comment]
FOUND IT AGAIN worried that I was going senile.

**Comment by OldSubSailor** [comment]
I went to the Homebrew Community and there has been some discussion about this path not working. One was another reading test failure but there was a few not working.

**Comment by w8sl** [comment]
https://github.com/w8sl/Ortho4XP/tree/Progressive_XP11

I will try to make a fresh install and see what happens, when I am back home next week. May be Homebrew have broken something again? They did it before.

**Comment by w8sl** [comment]
Just delete hidden file .zprofile and run these 2 commands. The only thing I have in mine is path to Homebrew

**Comment by OldSubSailor** [comment]
That was a disaster. Endless stream of “too many symbolic links" error

**Comment by w8sl** [comment]
etc/paths:

/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

users/my account/.zprofile:

eval "$(/opt/homebrew/bin/brew shellenv)"

etc/zprofile:

# System-wide profile for interactive zsh(1) login shells.

# Setup user specific overrides for this in ~/.zprofile. See zshbuiltins(1)
# and zshoptions(1) for more details.

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

**Comment by OldSubSailor** [comment]
I had seen the same thing in that. paths file earlier. 
I had to make another .zprofile file with bbedit.  I uninstalled Homebrew and reinstalled. I got everything working at first because of the initial path setting command lines. Then again no joy after the first session. I tried a path export command line variable change via .zshrc but that will not work, but will as a direct terminal command line input. 

export PATH=$PATH/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin/

**Comment by w8sl** [comment]
Seems like you are not alone:

https://geekchamp.com/how-fix-brew-command-not-found-on-mac-with-zsh/

**Comment by w8sl** [comment]
Found also this:

In my case, the thing was hidden in the line To update your account to use zsh, please run chsh -s /bin/zsh.

As I understood, the problem is in fact, that for any reason zsh was not a default shell interpreter in the system after a fresh update to macOS Sonoma. After execution of chsh -s /bin/zsh - the issue with "ignored" .zshrc disappeared.

**Comment by OldSubSailor** [comment]
I can try it, however, this computer came with Sonoma => zsh already installedSent from my iPhoneOn Apr 5, 2024, at 18:11, w8sl ***@***.***> wrote:﻿
Found also this:
In my case, the thing was hidden in the line To update your account to use zsh, please run chsh -s /bin/zsh.
As I understood, the problem is in fact, that for any reason zsh was not a default shell interpreter in the system after a fresh update to macOS Sonoma. After execution of chsh -s /bin/zsh - the issue with "ignored" .zshrc disappeared.

**Comment by w8sl** [comment]
Tested  with fresh install of Sonoma 14.4.1 
Set up as a new computer - nothing imported.
zsh works as expected. 
I can delete file /users/my_account/.zprofile. 
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/my_account/.zprofile    brings it back with no errors.
Homebrew installed with no problems 
echo $PATH on a completely fresh system + Homebrew looks like this:

/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin

I tested Install_Instructions on my 1.40 fork. The only thing missing was:

softwareupdate --install-rosetta

(necessary to run nvcompress)

I will test scenarios other to fresh install and report back

**Comment by w8sl** [comment]
Now I transferred my 10 years old account which went through Intel and M1 with remnants of Intel Homebrew showing some errors. Reinstalled Homebrew. 
Executed echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/my_account/.zprofile
Then
brew install python@3.11
For some reason I needed to restart shell twice but everything was working.

Installed Python 3.11 from python.org also to test further. Now my .zprofile looks like this:

eval "$(/opt/homebrew/bin/brew shellenv)"

Setting PATH for Python 3.11
The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.11/bin:${PATH}"
export PATH

Switching back to Homebrews Python was very easy:

1. Rename /users/my_account/.zprofile to something else
2. Rename /users/my_account/.zprofile.pysave to .zprofile
3. Restart shell

**Comment by OldSubSailor** [comment]
I finally got something to work, but I do not feel that it is a true long term solution. It took two path change edits to .zshrc:

export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
export PATH="/opt/homebrew/sbin:$PATH"

**Comment by w8sl** [comment]
I was also thinking about Apple support. Shell seems to ignore .zprofile for some reason - so it is not related to Homebrew. Nice it accepts .zshrc at least.

**Comment by OldSubSailor** [comment]
Unfortunately, the Community will rag you if they see any Homebrew stuff regardless if it is the fault of Homebrew or not. In the case above, it looks like the order of the PATH variable is now important. Homebrew in the lead works, while on the end did not, even in .zshrc.

**Comment by w8sl** [comment]
I have seen posts describing .zprofile file being corrupted in a strange way. Deleting it and rebuilding by:

echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/my_account/.zprofile

- should fix the problem. Seeing errors, while doing it, is certainly abnormal

**Comment by OldSubSailor** [comment]
Currently the path change has things working, do I want to mess with all the eval stiff again?

**Comment by w8sl** [comment]
I have it covered now - on my default branch (kind off)

**Comment by OldSubSailor** [comment]
I went through several deletes and rebuilds of .zprofile none of which worked. Homebrew refuses to consider that it is an issue on their end. Apple Support (the company that is) have never supported anything to do with using terminal, and the Community scoffs.

**Comment by w8sl** [comment]
I could not reproduce issue on my test install so far. May try next weekend at the earliest. Should we keep it open?

**Comment by OldSubSailor** [comment]
Sure we can close this. Either this is an M2, macOS or a hidden Homebrew issue.

**Comment by w8sl** [comment]
This is complex. Works similar on Linux:

https://serverfault.com/questions/901403/zsh-not-sourcing-zprofile

**Comment by OldSubSailor** [comment]
my path really looks complex:
 % echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
%

**Comment by OldSubSailor** [comment]
I looked for the .zshenv file before and do not have it; either locally nor in /etc.  I decided to leave the system files alone.

**Comment by w8sl** [comment]
I will test with .profile tomorrow and report back

**Comment by w8sl** [comment]
.profile doesn't work but .zlogin works on my end (same syntax as .zprofile)

**Comment by w8sl** [comment]
I have seen another computer with PATH to Homebrew defined as yours in .zshrc. There is no .zprofile file, but it works when created in BBEdit. I think you are good to go as is.

**Comment by OldSubSailor** [comment]
well, I broke down and performed a complete clean reinstall of the system software; messed up and forgot to make a copy of my .zshrc file (have one on my iMac in East Texas).  The path looks like the one that the Apple dudes talked about to start with.

**Comment by w8sl** [comment]
eval "$(/opt/homebrew/bin/brew shellenv)"   
in .zprofile
or
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"   
in  .zshrc

Both work and give exact same result:
echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin: ......

BBEdit can save .zshrc and .zprofile

**Comment by OldSubSailor** [comment]
the export in .zshrc only needs to be "run" one time, i.e. start terminal; then you can _comment them out_ because the path is set. 

For me after wiping the internal SSD, and reinstalling Sonoma (evidently I had a mixture of Ventura & Sonoma macOS [corruption?], I was able to reinstall Homebrew and use the
 {echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/***/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"}
command lines immediately after the Homebrew install and everything worked as it should. 
The line is in .zprofile and the path has been modified to include Homebrew.

**Comment by OldSubSailor** [comment]
Actually it turned out to be worse, it was not Ventura, but Big Sur that got snuck in there.

**Comment by w8sl** [comment]
BTW: "pip3.11 install gdal" is necessary, as only gdal for Python 3.12 is installed by default.

**Comment by w8sl** [comment]
It looks like most possible problems are covered now (updated instructions on default branch)

**Comment by OldSubSailor** [comment]
I found this on X-Plane. Org forum. 
At first I thought he had run into the security thing but he added these details. 

Here is something that is going on with another user, do you have any ideas,

Step 2 : Building mesh for tile +41-071 : 
--------

-> Modifying curv_tol weight map according to coastline location.
    * Recycling OSM data from ./OSM_data/+40-080/+41-071/+41-071_coastline.osm.bz2
-> Start of the mesh algorithm Triangle4XP.

WARNING: Triangle4XP could not achieve the requested quality (min_angle), most probably due to an uncatched OSM error.
It will be tempted now with no angle constraint (i.e. min_angle=0).

ERROR: Triangle4XP really couldn't make it !

If the reason is not due to the limited amount of RAM please
file a bug including the .node and .poly files that you
will find in /Users/ronaldchen/Desktop/XP12/Custom Scenery/zOrtho4XP_+41-071.

**Comment by w8sl** [comment]
Unmodified 130 doesn't work on Sonoma as Triangle4XP.app is not accepted filename. I have changed to just Triangle 4XP on my XP11 fork which works. Even source files need to be edited accordingly. I have suggested 2 other solutions on the same thread. See posts from 03 and 04 April.

**Comment by OldSubSailor** [comment]
So that was you on that thread then, I was wondering if that was a version of your “name” used here here. The first time that he posted, it looked like he ran into the Mac security beast, it gives a very similar message. 
It will mess up the Triangulate and Build Imagery steps on a new install of Ortho 1.3 or 1.4.
So he continues to insist on 1.3 for some reason then and I just pointed out that you said to use 1.4. 
The only issue that I have now, is that the new sat shots for the maps look really bad for the most part when compared to some of the older ones. A lot of Louisiana looks overly bland now in Google Maps, but that is not Ortho’s fault.

**Comment by w8sl** [comment]
There is a nice update to Mapbox.lay posted 06.04.
"Maptiler as provider"
3 options in the last post. Only one is needed. 
(GDAL is not working correctly in venv BTW.
We may stay on a standard install for now)

**Comment by w8sl** [comment]
GDAL works in Python 3.11 venv on macOS! It is only chmod +x, drag and drop venv 3.11 install file, repeat for start file. Then, drop venv 3.11 install file into terminal, enter. Drop start file into terminal, enter. All on my default branch of 1.40

**Comment by OldSubSailor** [comment]
I am trying to work with this guy, & trying to work with version 1.4 and thought we got all the pip packages and brew stuff installed. 
Using the Ortho Code from your Github. 
But as soon as he tried to call Ortho from terminal, he got:
Traceback (most recent call last):

  File "/Users/ronaldchen/Desktop/Ortho4XP-master/Ortho4XP.py", line 9, in <module>

    import O4_Imagery_Utils as IMG

  File "/Users/ronaldchen/Desktop/Ortho4XP-master/./src/O4_Imagery_Utils.py", line 2, in <module>

    import O4_Mask_Utils as MASK

  File "/Users/ronaldchen/Desktop/Ortho4XP-master/./src/O4_Mask_Utils.py", line 7, in <module>

    from PIL import Image, ImageDraw, ImageFilter, ImageOps

ImportError: cannot import name 'Image' from 'PIL' (unknown location)

Any earthy idea as to what is going on? Never even got Ortho up.

**Comment by w8sl** [comment]
Started from a wrong directory? I will add start app later today. (script changing directory)

**Comment by OldSubSailor** [comment]
Please be patient, you have two guys in our late 70s working through this, remotely.

**Comment by OldSubSailor** [comment]
> BTW: "pip3.11 install gdal" is necessary, as only gdal for Python 3.12 is installed by default.

I am going over this conversation again. I never did run this install, however, I am having no issues with Ortho4XP 1.4. builds for X-Plane 12 => goal does not show up in the pip3.11 listing. Do you think that I need to go ahead and install then?

**Comment by OldSubSailor** [comment]
This was his pip listing last night:
here is what I get with pip3.11 list

Package            Version

------------------ --------

certifi            2024.2.2

chardet            5.2.0

charset-normalizer 3.3.2

GDAL               3.9.0

idna               3.7

numpy              1.26.4

pillow             10.3.0

pip                24.0

pyproj             3.6.1

requests           2.31.0

Rtree              1.2.0

scikit-fmm         2023.4.2

setuptools         69.2.0

shapely            2.0.4

urllib3            2.2.1

wheel              0.43.0

**Comment by w8sl** [comment]
As of GDAL 3.9 I must do complete reinstall and see what happens. It is a major update.

**Comment by OldSubSailor** [comment]
so I need to add GDAL 3.9 although things are working fine on Sonoma  also then? and did you just revise the script? if so then I would need to revise the text file??  

With regard to pillow, I asked him to run
pip3.11 show pillow 

pip3.11 check pillow

**Comment by OldSubSailor** [comment]
￼
Perhaps this will not hide the email looking files.

**Comment by w8sl** [comment]
Downloaded a fresh copy of O4XP 1.40 from default branch on my fork.
Wiped out opt/Homebrew, deleted .zprofile. Started timer.
Installed Homebrew. 

Then did: 
chmod +x ./z_Install_O4XP_macOS_Python3.11_Venv.sh
the same for: z_Start_O4XP_PythonVenv.sh

Edited "z_Install_O4XP_macOS_Python3.11_Venv.sh" and uncommented line 5 with "brew install" command, as I wanted full install from scratch.

Then:

1. drag-and-drop "z_Install_O4XP_macOS_Python3.11_Venv.sh" into terminal, enter

Waited few minutes

2 drag-and-drop "z_Start_O4XP_PythonVenv.sh" into terminal, enter

Ortho4XP started normaly. Did step one for tile 33 -119 using USGS NED1/3 elevation data from a drop-down list

![Result](https://github.com/w8sl/Ortho4XP/assets/100048048/4757a80a-a62f-4dad-b4d3-e25e83ea54d5)

**Comment by OldSubSailor** [comment]
We are trying to run Sonoma, none of the Ventura stuff.We used the files listing from the "regular" .shfile. Still no go. Sent from my iPhoneOn May 15, 2024, at 13:01, w8sl ***@***.***> wrote:﻿
Downloaded a fresh copy of O4XP 1.40 from default branch on my fork.
Wiped out opt/Homebrew, deleted .zprofile. Started timer.
Installed Homebrew.
Then did:
chmod +x ./z_Install_O4XP_macOS_Python3.11_Venv.sh
the same for: z_Start_O4XP_PythonVenv.sh
Edited "z_Install_O4XP_macOS_Python3.11_Venv.sh" and uncommented line 5 with "brew install" command, as I wanted full install from scratch.
Then:

drag-and-drop "z_Install_O4XP_macOS_Python3.11_Venv.sh" into terminal, enter

Waited few minutes
2 drag-and-drop "z_Start_O4XP_PythonVenv.sh" into terminal, enter
Ortho4XP started normaly. Did step one for tile 33 -119 using USGS NED1/3 elevation data from a drop-down list
Result.jpg (view on web)

**Comment by OldSubSailor** [comment]
Or is this no longer valid for M1 or M2 Sonoma Macs?Sent from my iPhoneOn May 15, 2024, at 13:01, w8sl ***@***.***> wrote:﻿
Downloaded a fresh copy of O4XP 1.40 from default branch on my fork.
Wiped out opt/Homebrew, deleted .zprofile. Started timer.
Installed Homebrew.
Then did:
chmod +x ./z_Install_O4XP_macOS_Python3.11_Venv.sh
the same for: z_Start_O4XP_PythonVenv.sh
Edited "z_Install_O4XP_macOS_Python3.11_Venv.sh" and uncommented line 5 with "brew install" command, as I wanted full install from scratch.
Then:

drag-and-drop "z_Install_O4XP_macOS_Python3.11_Venv.sh" into terminal, enter

Waited few minutes
2 drag-and-drop "z_Start_O4XP_PythonVenv.sh" into terminal, enter
Ortho4XP started normaly. Did step one for tile 33 -119 using USGS NED1/3 elevation data from a drop-down list
Result.jpg (view on web)

**Comment by OldSubSailor** [comment]
I am trying to avoid anything but the plain python commands Sent from my iPhoneOn May 15, 2024, at 13:01, w8sl ***@***.***> wrote:﻿
Downloaded a fresh copy of O4XP 1.40 from default branch on my fork.
Wiped out opt/Homebrew, deleted .zprofile. Started timer.
Installed Homebrew.
Then did:
chmod +x ./z_Install_O4XP_macOS_Python3.11_Venv.sh
the same for: z_Start_O4XP_PythonVenv.sh
Edited "z_Install_O4XP_macOS_Python3.11_Venv.sh" and uncommented line 5 with "brew install" command, as I wanted full install from scratch.
Then:

drag-and-drop "z_Install_O4XP_macOS_Python3.11_Venv.sh" into terminal, enter

Waited few minutes
2 drag-and-drop "z_Start_O4XP_PythonVenv.sh" into terminal, enter
Ortho4XP started normaly. Did step one for tile 33 -119 using USGS NED1/3 elevation data from a drop-down list
Result.jpg (view on web)

**Comment by OldSubSailor** [comment]
I'm trying to get a Sonoma version of David's instructions working in the long run. Sent from my iPhoneOn May 15, 2024, at 13:01, w8sl ***@***.***> wrote:﻿
Downloaded a fresh copy of O4XP 1.40 from default branch on my fork.
Wiped out opt/Homebrew, deleted .zprofile. Started timer.
Installed Homebrew.
Then did:
chmod +x ./z_Install_O4XP_macOS_Python3.11_Venv.sh
the same for: z_Start_O4XP_PythonVenv.sh
Edited "z_Install_O4XP_macOS_Python3.11_Venv.sh" and uncommented line 5 with "brew install" command, as I wanted full install from scratch.
Then:

drag-and-drop "z_Install_O4XP_macOS_Python3.11_Venv.sh" into terminal, enter

Waited few minutes
2 drag-and-drop "z_Start_O4XP_PythonVenv.sh" into terminal, enter
Ortho4XP started normaly. Did step one for tile 33 -119 using USGS NED1/3 elevation data from a drop-down list
Result.jpg (view on web)

**Comment by w8sl** [comment]
https://forums.x-plane.org/index.php?/forums/topic/282950-ortho4xp-m1-mac/&do=findComment&comment=2706293

**Comment by OldSubSailor** [comment]
> https://forums.x-plane.org/index.php?/forums/topic/282950-ortho4xp-m1-mac/&do=findComment&comment=2706293
> 
> If the path is broken, it is necessary to rebuild .zprofile

HIs homebrew path?
echo $PATH
 brought up:

 

/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin

**Comment by OldSubSailor** [comment]
inspection of path directory showed that some of the packages had simply 'gone' we reinstalled all pip packages and are have Ortho4 at least started again.

**Comment by w8sl** [comment]
Path looks correct. I have confirmed that Mac install script works correctly. Python 3.11 venv for Mac works. There is also universal venv for all Unix based systems incl. macOS which installs O4XP including scikit-fmm on Python 3.12.  GDAL 3.9 is fine. No reason to look back.

**Comment by OldSubSailor** [comment]
> As of GDAL 3.9 I must do complete reinstall and see what happens. It is a major update. My updated script should work.

Regarding GADL 3.9
I still remain confused seeing as how I am running Ortho4XP1.40 with no pip version of GDAL installed; however; I decided to go ahead to install it last night as usual, i.e. _pip3.11 install gdal_ .  Things cranked and chugged and I got a screen load of text but finally ended up with it not being installed and some reference to python3.12.
Next, based on another of your posts, I tried:
pip3.11 install gdal==$(gdal-config --version)
and gdal was installed > GDAL 3.8.5

Now at this point, Ortho4 comes up and runs. I have yet to try and create a tile to see what happens. 
Any comments? Do you want me to uninstall 3.8.5 and try to install again so I can give you the details of the error that I saw last night?
About all that I can tell you about the Master that I am using is the creation date is 4/3/24, if that helps.

**Comment by w8sl** [comment]
**pip3.11 install gdal==$(gdal-config --version)**   is the right way to go. This command installs via pip3.11 python3.11 part of exact same version of GDAL that was installed systemwide via brew. You don't need to upgrade, if it is working for you. You must re-run **pip3.11 install gdal==$(gdal-config --version)**, when gdal eventually gets updated by brew Auto-Update. 
NED1/3 is available from drop-down menu on 1.40 - it is easy to test. It requires gdal_array function, which btw is not tested properly in the current version of O4XP. 
It should be something like:
try:
    from osgeo import gdal
    from osgeo import gdal_array
    has_gdal = True
    gdal.UseExceptions()
except:
    has_gdal = False

**Comment by OldSubSailor** [comment]
Used my Ortho4, and NED 1 and 1/3 and had no issues creating a down and dirty ZL12 tile.

**Comment by OldSubSailor** [comment]
As of 4/2025 my recommendation for all Mac computers with Apple silicon is to go with Without Homebrew method.

**Comment by w8sl** [comment]
I’ll address that when the GDAL-free update is ready. GDAL requires the use of Homebrew. It’s possible to create GeoTIFFs using Rasterio. The download of elevation data is already handled by Rasterio.

**Comment by OldSubSailor** [comment]
Really? I do not have any form of Homebrew installed on my Mac mini M2, and I used the without Homebrew installation with no issues.  However, I have not made GeoTIFFs, just plain old tiles for flying around;  have I misunderstood you again?
What do we gain/loose?

**Comment by w8sl** [comment]
Ready!
https://github.com/w8sl/Ortho4XP/blob/Progressive_140/Install_Instructions.md

**Comment by w8sl** [comment]
Another also user confirmed it works this way with XP11!
I prefer [Progressive_130](https://github.com/w8sl/Ortho4XP/tree/Progressive_130) for XP11 and XP12.09. It’s equally updated and a bit faster (most important difference is 2D water). 

Of course, it is a good idea to have all tiles ready for XP12.2+ 
BTW: ZL20 may work fine with XP11, but it may be too much for XP12

**Comment by OldSubSailor** [comment]
So far ZL 20 has worked on XP12 for me.

**Comment by OldSubSailor** [comment]
Progressive_130 
Install Mac sh
Error returned on 
brew install python@3.11-tk
Warning: No available formula with the name "python@3.11-tk".

**Comment by OldSubSailor** [comment]
@w8sl 
I appreciate the link to Progressive_130. It appears to be working on my old 2017 iMac and XP11. However, when I made a tile using progressive for airport zl the preview does not look like it made progressive airports(zl 20) as it does for Progressive_140.
A clipped screenshot is attached. It does show custom ZLs as expected.  

<img width="332" alt="Image" src="https://github.com/user-attachments/assets/5ab4bde9-3cff-4e9d-aa06-47ea93c83d43" />

**Comment by w8sl** [comment]
Officially only zl 19 is supported.  Small change to the source code is required to enable zl 20. 
On progressive_130 it is defined in: 

line 365, O4_Common_Types.py:   __ZL_MAX__ = 19  
It can be changed to 20 which is the max possible value

(I will check tomorrow, why it is working with Progressive_140)

**Comment by OldSubSailor** [comment]
Ok, I will try again.

**Comment by OldSubSailor** [comment]
I set it to 19 and again it seems to not create airports as done with Progressive_140 Preview. 

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/edcf5c3e-2aa8-4ca1-b11a-5d5465c6ff79" />
<img width="198" alt="Image" src="https://github.com/user-attachments/assets/968deda5-ee8d-4aa8-aea4-200d6f5ce2d9" />

**Comment by OldSubSailor** [comment]
@w8sl 
Here is a for instance example 
This is a clipped screenshot from a previously created tile, before I had Progressive_130, some time ago. So Hi ZL airports would have been set to True. Preview in Progressive_130 shows this airport as . . . 

<img width="405" alt="Image" src="https://github.com/user-attachments/assets/19cdf122-df35-40c2-b3ed-2716ae8dab94" />

**Comment by w8sl** [comment]
Progressive zones are built from the X-Plane airport database. 
Set the **xplane_install_dir** in the Ortho4XP Config settings (path to “X-Plane 11” top directory). 
**cover_extent** works only with “True” and “ICAO”. Progressive zone size is defined by **cover_fov**.

**Comment by OldSubSailor** [comment]
Ok, I do admit that I did see:
"Set the xplane_install_dir in the Ortho4XP Config settings (path to “X-Plane 11” top directory)." when reading about 130 earlier. ***
Which is indeed different from the instructions in Progress_140; and I further admit that I did not understand it. I sort of understand the third sentence, I only provided the example as a "history" demo.
***So is the path to the XP11 application, or the folder (i.e. top directory) that it is in? Perhaps an example here is also needed such as in 140?

**Comment by OldSubSailor** [comment]
Well, heck, it must be too early for my old age. I was "seeing" Overlay src not Install dir. , Silly me. over lay src should still be XP11 global, seeing as that is what we are using. Back to the drawing board.

**Comment by OldSubSailor** [comment]
That seems to have gotten it done; however; I had to run Build Imagery/DSF twice to get the high_zl_airports built.

**Comment by OldSubSailor** [comment]
For a better example, I set the Airport Custom ZL at 19 and at 20 and Previewed them using Zone List Editor button. This shows  the difference at what Build Imagery/DSF is supposed to do, I think. 

Airport ZL 19:
<img width="459" alt="Image" src="https://github.com/user-attachments/assets/abb39c75-247e-4e56-a287-d8b7c1f0e106" />

Airport ZL 20:
<img width="375" alt="Image" src="https://github.com/user-attachments/assets/c93369c8-d42b-4bfd-86e8-259431e0c762" />

**Comment by OldSubSailor** [comment]
Just for fun, I did try ZL 20 airports and it accepted it and tried. The result was pretty ugly.

**Comment by OldSubSailor** [comment]
> A nice feature is "Show Existing DSF Layout". Very useful to verify what was actually created

Indeed it did, so I expected "pretty ugly."

I have a question regarding something that terminal reports when starting progressive_130:
".zprofile:5: no such file or directory: /usr/local/bin/brew"
I used the macOS quick install method, and it worked just fine, so no homebrew was involved, and it is not on my iMac. 
The program apparently working fine, so the above ".zprofile:5..." does not seem to be an issue, but does it need to be reported  after starting, i.e. double clicking the z_Start_04XP.command?
